//
//  Text.swift
//  CommaUser
//
//  Created by Marco Sun on 16/5/17.
//  Copyright © 2016年 LikingFit. All rights reserved.
//

import Foundation

struct Text {
    
    static let Login      = "登录"
    static let Logout      = "退出登录"
    static let Reg        = "注册"
    static let Delete        = "删除"
    static let UnPublish  = "未公布"
    static let Interest   = "关注"
    static let Hate       = "不感兴趣"
    static let Close      = "关闭"
    static let Complete   = "完成"
    static let Cancel     = "取消"
    static let Sure       = "确定"
    static let Next       = "下一步"
    static let Save       = "保存"
    static let NotSave    = "不\(Save)"
    static let Reload     = "重新加载"
    static let Nodata     = "暂无内容"
    static let MsgDefault = "请稍候..."
    static let MsgError   = "操作失败！"
    static let MsgSuccess = "操作成功！"
    static let Loading    = "正在登录..."
    static let ToSetting  = "去设置"
    static let NotNow  = "暂不"
    static let PhotoLibray  = "相册"
    static let Camera  = "相机"
    static let Auth  = "授权"
    static let Known  = "知道了"
    static let Appointment  = "立即预约"
    static let BuyClass  = "购买课程"
    static let NoClass  = "暂无课程"
    static let Exchange  = "兑换"
    static let BecomeCoachSubmit = "立即提交"
    static let OK  = "好的"
    static let Reminding  = "提示"
    static let ToBuyCard  = "去购卡"
    static let More = "更多"
    static let Confirm = "确认"
    static let waitConfirm = "待\(Confirm)"
    static let Yes = "是"
    static let No = "否"
    static let Refuse = "拒绝"
    static let Accept = "接受"
    
    static let TokenOutDate     = "登录状态已过期"
    static let NetErrorMessage  = "网络出错，请检查网络后重试"
    static let PlayFailureMessage  = "播放失败，请稍后重试"
    static let ServerErrorMessage = "数据异常!\n请退出App后重试\n或者联系管理员！"
    static let IsMatching       = "正在为你匹配..."
    static let BadgeEmpty       = " "
    static let MsgUploading     = "正在上传..."
    static let MsgUploaded      = "上传成功!"
    static let UploadError      = "上传失败!"
    
    static let FeeGroupClass              = "付费团体课"
    static let FreeGroupClass              = "免费团体课"
    static let SelfServiceClass              = "自助团体课"
    static let GroupClass              = "团体课"
    static let littleGroupClass              = "小团体课"
    static let GroupFullClass          = "团操课"
    static let PrivateClass              = "私教课"
    
    static let MemberStatusInitMsg      = "未知状态，请反馈此问题"
    static let ContactCustomerServer = "确认联系客服?"
    static let ContactBusinessServer = "确认拨打商务合作电话?"
    static let MakeSureCall = "确认拨打电话?"
    
    static let StrRefreshing            = "\(AppName)正在帮你刷新..."
    static let SaveReminding            = "你要保存你的数据吗？"
    static let EmailInvalid            = "邮箱格式无效"
    static let Split              = ","
    static let Point              = "・"
    
    static let NoLocationAuth            = "定位授权未开启"
    static let NoAuth                   = "授权未开启"
    static let OpenInSetting            = "请在系统设置中开启"
    static let OpenInSettingLocation            = "请在系统设置中开启定位服务"
    static let LocationAuthMessage       = "请在系统设置中开启定位服务\n设置->隐私->定位服务->\(AppName)"
    static let LocationSuccess      = "定位成功!"
    static let LocationFailed       = "定位失败!"
    static let ObtainLocation       = "获取定位地址"
    static let CantScanMap       = "定位失败，无法获取城市地图"
    static let RangeWarning = "请输入规定范围内课程数"
    
    
    static let Course = "课程"
    static let Order = "订单"
    static let MemberCard = "会员卡"
    static let Coupon = "优惠券"
    static let Impact = "Impact"
    static let Class = "约课"
    static let Feeding = "营养餐"
    static let BuyCard = "购卡"
    static let Mine = "我"
    static let BecomeLikingCoach = "成为教练"
    static let JoinLiking = "联系加盟"
    static let AboutUs = "关于我们"
    static let ClearCache = "清除缓存"
    static let ToScore = "去评分"
    static let OrderSuccess = "预约成功！"
    static let OrderFailed = "预约失败！"
    static let PaySuccess = "支付成功！"
    static let PayDealing = "正在处理中"
    static let PayFailure = "支付失败"
    static let SendFailure = "发送失败"
    static let PayCancel = "支付已取消"
    static let PayConnectBreak = "网络连接出错"
    static let NoWeixin = "您还没有安装微信客户端,无法使用微信支付功能"
    static let EncourageForFriends = "邀请好友奖励"
    static let ChooseFirst = "请先选择训练项目"
    static let ChooseSubscribeTime = "选择预约时间"
    static let Shanghai = "上海市"
    static let BuyNow = "立即购买"
    static let PutPhoneNumber = "输入手机号"
    static let PutValidNumber = "输入验证码"
    static let ObtainValidNumber = "获取验证码"
    static let LogoutSuccess = "退出成功"
    static let LogoutFailure = "登出失败"
    static let LoginSuccess = "登录成功"
    static let CouponSuccess = "兑换成功!"
    static let OrderCancel = "支付时间已到，订单已取消"
    static let PressToScanStore = "点击查看场馆详情"
    static let PushAlertTitle = "您好"
    static let PushAlertCancel = "知道了"
    static let PushAlertGoCheck = "查看"
    static let PushAlertGoUpdate = "去升级"
    static let SoldOut = "已售罄"
    static let WaitForYou = "等你首尝"
    static let CantOverTen = "营养餐单次购买总量不可以大于10份哦~"
    static let DoYouWannaLogout = "确认要退出登录吗？"
    static let ConfirmCancelCourse = "确认取消预约课程"
    static let ConfirmRefuseCourse = "确认要拒绝课程吗?"
    static let ConfirmAcceptCourse = "确认要接受课程吗?"
    static let ConfirmDoneCourse = "确认完成课程"
    static let ConfirmCancelFeeding = "确认取消购餐"
    static let ConfirmDoneFeeding = "确认已经取餐"
    static let NotCancel = "暂不取消"
    static let NotRefused = "暂不拒绝"
    static let NotAccepted = "暂不接受"
    static let Explain = "说明"
    static let ContactCustomerService = "联系客服"
    static let UnknowCity = "定位失败"
    static let UnknowCityID = "0"
    static let ShanghaiCityID = "310100"
    static let XuHuiDistrictID = "310104"
    static let AppointmentFull = "预约已满"
    static let OpenGeneration = "开启智能健身"
    static let GoToAppStore = "去更新"
    static let Locating = "定位中..."
    static let NoContent = "暂时没有内容"
    static let GetFailed = "获取失败"
    static let PleaseReLocate = "定位失败，请重新定位"
    static let NowErrorPleaseUpdate = "当前网络异常，请先刷新首页，再尝试切换！"
    static let CityHasNoGym = "当前定位城市尚未开通服务，敬请期待"
    static let Wrong = "错误"
    /* 时间 */
    static let Minute = "分"
    static let Second = "秒"
    static let Year = "年"
    static let Month = "月"
    static let Day = "日"
    static let MinuteFull = "分钟"
        
    /* 单位 */
    static let Times = "次"
    static let TimesFull = "次数"
    static let Person = "人"
    static let Yuan = "元"
    static let Wei = "位"
    static let KmChinese = "公里"
    static let Speed = "公里/小时"
    
    /**/
    static let TryAgainLater = "稍后再试"
    static let SearchSuccess = "搜索成功"
    static let WeChatPay = "微信支付"
    static let WeChat = "微信"
    static let AliPay = "支付宝支付"
    static let ShareToWeChatFriend = "分享给微信好友"
    static let ShareToWeChatFriendCircle = "分享到朋友圈"
    static let UninstalledWeChatNotice = "您还没有安装微信客户端,无法通过微信分享"
    static let LookStore = "查看场馆"
    static let PleaseInputCorrectBytes = "请输入正确的位数!"
    static let NetworkPoorNotice = "网络好像不给力哦"
    static let Refresh = "刷新"
    static let CurrentCity = "当前城市"
    static let NoMoreDataNotice = "—— 好,就到这儿了 ——"
    static let Ignore = "跳过"
    static let SendAgain = "重新发送"
    static let LoginMeanAgree = "登录即为同意"
    static let UserAgreement = "《用户协议》"
    static let IntelligentGym = "智能健身房"
    static let IntelligentGymAd = "让健身这件事智能一点点"
    static let ExclusiveCoach = "专属私教"
    static let ExclusiveCoachAd = "给你最需要的专业指导"
    static let FitData = "健身数据"
    static let FitDataAd = "科学记录健身数据"
    static let Announcement = "公告"
    static let Message = "消息"
    static let PasswordOpenDoor = "密码开门"
    static let TapToBuyCard = "点击购卡"
    static let OpenIntelligentFit = "即刻开启智能健身之旅"
    static let NoCourseNow = "暂时没有课程"
    static let NoAnnouncementNow = "暂无公告"
    static let AppointSelfHelpCourse = "预约自助团体课"
    static let CancelAppoint = "取消预约"
    static let ConfirmAppoint = "确认预约"
    static let CourseNotStart = "课程尚未开始"
    static let CourseOngoing = "课程进行中"
    static let CourseNotiStr = "你有新的课程预约待处理！"

    
    static let ForClass = "待上课"
    static let InClass = "上课中"
    static let HaveClass = "已上课"
    static let HaveFrozen = "已冻结"
    static let UnPay = "未结算"
    static let Settled = "已结算"
    static let Deduction = "已扣课"
    static let TurnBack = "已退课"
    static let Finished = "已结束"
    static let Canceled = "已取消"
    static let Paid = "已支付"
    static let NotStart = "未开始"
    static let OnGoing = "进行中"
    static let Submitted = "已提交"
    static let CourseIntroduction = "课程介绍"
    static let Time = "时间"
    static let Store = "场馆"
    static let Coach = "教练"
    static let Address = "地址"
    static let Intensity = "强度"
    static let StoreIntroduction = "场馆介绍"
    static let ApplyMember = "报名会员"
    static let SupportTeachGym = "支持教学健身房"
    static let TrainItem = "训练项目"
    static let Share = "分享"
    static let PleaseTryAgainLater = "请稍后再试"
    static let PleaseChooseCardType = "请先选择卡类型"
    static let HasBenefit = "已优惠"
    static let StoreName = "场馆名称"
    static let StoreAddress = "场馆地址"
    static let ExpiryDate = "有效期"
    static let Place = "地点"
    static let JoinNum = "上课人数"
    static let CourseTime = "课程时间"
    static let Zhifubao = "支付宝"
    static let JoinTimes = "上课次数"
    static let CoursePlace = "上课地点"
    static let MyAppointment = "我的预约"
    static let MyAppointmentList = "预约课程列表"
    static let MyCoupon = "我的优惠券"
    static let NoCouponNow = "暂无优惠券"
    static let NoAnnounceNow = "暂时没有公告"
    static let NoMessageNow = "暂时没有消息"
    static let InputValidCouponNotice = "请输入有效的优惠码"
    static let InputCorrectExchangeNotice = "请输入正确的兑换码"
    static let InputCouponCode = "输入兑换码"
    static let Expire = "到期"
    static let OpenDoor = "开门"
    static let GetDoorPassword = "获取密码开门"
    static let GetInDoorPassword = "获取进门密码"
    static let GetOutDoorPassword = "获取出门密码"
    static let BraceletOpenDoorNotice = "使用手环刷门禁开门"
    static let MyGym = "我的健身房"
    static let CurrentCityUnOpenNow = "当前城市尚未开通"
    static let PleaseWaiting = "敬请期待..."
    static let Appellation = "名称"
    static let Duration = "时长"
    static let AttendCourse = "上课"
    static let SwitchStore = "切换场馆"
    static let NearestToYou = "距您最近"
    static let BuyCardMeanAgree = "购卡即同意"
    static let AlreadyReadAndAgree = "已阅读"
    static let BuyPrivateMeanAgree = "购买私教课即同意"
    static let PlatformMemberProtocol = "《平台会员协议》"
    static let PrivateMemberProtocol = "《平台私教协议》"
    
    
    static let TeamCourseMemberProtocol = "《团操课协议》"
    static let littleGroupCourseMemberProtocol = "《购买协议》"
    static let littleGroupNotenNeedProtocol = "《注意事项及运动风险免责声明》"

    
    static let CardRenewal = "续卡"
    static let CardUpgrade = "升级卡"
    static let MindBuyCardWhenLocateFail = "定位失败，请谨慎购买会员卡"
    static let Buy = "购买"
    static let NotForBuy = "暂不购买"
    static let CardAbsenceNotice = "无卡用户或会员卡剩余有效期太短，请购卡后重试"
    static let CardOtherGymOwnedNotice = "您的会员卡不在该健身房下，请切换至购卡健身房后重试"
    static let ChooseCourceNotice = "请选择锻炼课程"
    static let Distance = "距离"
    static let Consume = "消耗"
    static let TodayTrainTime = "今日训练时间"
    static let UnLogin = "未登录"
    static let GoToAppoint = "去预约"
    static let InviteFriends = "邀请好友"
    static let LeftCourseTimes = "剩余上课次数"
    static let CourseInfo = "课程详情"
    static let ContactCoach = "联系教练"
    static let CourseItem = "课程项目"
    static let OrderNumber = "订单号"
    static let OrderTime = "下单时间"
    static let Price = "价格"
    static let Benefit = "优惠"
    static let Done = "完成"
    static let WrittenOffCourse = "销课"
    static let BreakAppoint = "失约"
    static let HasNoOrderNow = "暂时没有订单"
    static let GoToOrder = "去下单"
    static let FlawNumber = "流水号"
    static let LeftPayTime = "剩余支付时间"
    static let GoToPay = "去支付"
    static let HasNoMemberCardNow = "暂时没有会员卡"
    static let Renewal = "续"
    static let Upgrade = "升级"
    static let ValidityPeriod = "有效时间"
    static let MyMemberCard = "我的会员卡"
    static let CardNo = "卡号"
    static let ApplyCardTme = "办卡时间"
    static let GymName = "健身房名称"
    static let GymAddress = "健身房地址"
    static let UsePeriod = "使用时段"
    static let BuyLong = "购买时长"
    static let OrderDetailInfo = "订单详情"
    static let BuyMode = "购买类型"
    static let PayMode = "支付方式"
    static let DiscountAmount = "优惠金额"
    static let PayAmount = "支付金额"
    static let ModifyPersonalInfo = "修改个人资料"
    static let Gender = "性别"
    static let Male = "男"
    static let Female = "女"
    static let Nickname = "昵称"
    static let BodyHeight = "身高"
    static let BodyWeight = "体重"
    static let Age = "年龄"
    static let InputNewMessage = "请输入新的"
    static let PleaseInputCorrectNumber = "请输入正确的数字"
    static let NicknameInputLimite = "请输入15个字符以内,不包含特殊字符的昵称"
    static let HeightInputLimite = "请输入可选范围50-250cm内的身高值"
    static let WeightInputLimite = "请输入可选范围25-200kg内的体重值"
    static let PleaseChooseBirthday = "请选择生日"
    static let BirthdayInputLimite = "生日不能早于1950年，不能晚于今天哦！"
    static let PleaseInputNickName = "请输入昵称"
    static let ChooseGender = "选择性别"
    static let Birthday = "出生日期"
    static let InputBirthday = "填写出生日期"
    static let InputHeight = "填写身高"
    static let InputWeight = "填写体重"
    static let History = "历史"
    static let InputNickname = "输入昵称"
    static let ModifyDefaultNickname = "修改默认昵称"
    static let AddIcon = "添加头像"
    static let TapToUploadIcon = "点击上传头像"
    static let ChooseBirthYearMonth = "选择出生年月"
    static let PickerCity = "请选择城市"
    static let PleaseChoose = "请选择"
    
    
    /* 体测 */
    static let HistoryRecode = "历史记录"
    static let AnalysisResult = "┃分析结论:"
    static let Level_High = "高"
    static let Level_Low = "低"
    static let Level_Standard = "标准"
    static let Level_Offset_High = "偏高"
    static let Level_Offset_Low = "偏低"
    static let Level_Normal = "正常"
    static let PersonalData = "个人数据"
    static let PersonalBodyTestData = "个人体测数据"
    static let TodayTrain = "今日训练"
    static let BraceletData = "手环数据"
    static let BodyTestHistory = "体测历史"
    static let BodyTestDate = "体测时间"
    static let BodyTestData = "体测数据"
    static let MoreAdviceNotice = "更多建议请咨询店内教练"
    static let TestTime = "测试时间"
    static let BodyTestScore = "体测评分"
    static let ChooseHeight = "选择身高"
    static let ChooseWeight = "选择体重"
    static let BirthYearAndMonth = "出生年月"
    static let DoneInfoSetting = "完成个人信息设置"
    
    
    /* JoinApply Strings*/
    static let Name = "姓名"
    static let Phone = "联系电话"
    static let CompelteSubmitInfo = "请完善审核信息"
    static let InvalidMobile = "无效手机号"
    static let JoinApplySubmitTipInfo = "提交成功后s%会与您联系,请耐心等待"
    static let Bussiness = "商务人员"
    static let Office = "工作人员"
    static let SubmitJoinApplySuccess = "提交成功"
    static let NoSelectEnableTime = "没有可用的取餐时间!"
    static let ChooseTimeFirst = "请先选择取餐时间!"
    /* JoinApply Strings*/
    
    //MARK: - 蓝牙/手环
    static let BindBracelet = "绑定手环"
    static let MyBracelet = "我的手环"
    static let NameKey = "当前设备"
    static let MACKey = "手环MAC地址"
    static let VersionKey = "固件版本号"
    static let lookBraceletDataNotice = "您成功开启了手环数据功能\n快去我的信息界面查看数据吧！"
    
    static let ActivityEnableNotice = "*升级卡种以原价升级，不参加活动"
    static let SyncFailStr = "同步失败"
    static let SyncStartStr = "同步开始"
    static let SyncSuccess = "同步成功"
    static let ConnectFailStr = "连接失败"
    static let BraceletConnectFailStr = "手环连接失败"
    static let BraceletUnLink = "手环未连接"
    static let UnkownErrorStr = "未知错误，请稍后重试"
    static let ShakeToSyncData = "摇一摇同步数据"
    static let MindLinkBracelet = "请先连接手环"
    static let Linking = "连接中"
    static let ScanFailStr = "没能扫描到您的手环，请把手环放到手机附近后重试"
    static let DisconnectStr = "手环断开连接，请把手环放到手机附近后重试"
    static let ConnectFailFullStr = "手环连接失败，请把手环放到手机附近后重试"
    static let UnKownConnectFailStr = "未知错误，请稍后重新连接手环"
    static let ConnectTimeoutStr = "连接超时，请稍后重新连接手环"
    static let ToBind = "去绑定"
    static let OccurError = "出错"
    static let MineBind = "您的手环还没有绑定，请到绑定手环页面进行绑定"
    static let Retry = "重试"
    static let TodayData = "今日数据"
    static let TotalMove = "总运动数据"
    static let TodayStep = "步数"
    static let HeartRate = "心率"
    static let Total = "总"
    static let StepTimes = "步数"
    static let BluetoothUsage = ["1.请确保手机蓝牙打开","2.请确保手环有电","3.让手机靠近手环（在5米范围内）"]
    static let MacErrorNotice = "如果未搜索到设备，请咨询教练"
    static let TapToSearch = "点击搜索"
    static let BibasicBraceletLimiteStr = "只有二代手环用户才能绑定哟~"
    static let LinkFailWhenPowerOffStr = "手环连接失败，请确认蓝牙是否开启"
    static let LinkFailHintRetry = "手环连接失败，请稍后重试"
    static let BluetoothPowerOffStr = "蓝牙未开启"
    static let Open = "开启"
    static let YourDevice = "您的设备"
    static let ScanNoResultStr = "没有搜索到？点击重新搜索"
    static let Link = "连接"
    static let Setting = "设置"
    static let HintPowerOn = "打开蓝牙允许手环连接"
    static let UnbindStr = "解除绑定"
    static let UnBindFailNotice = "解绑失败，请稍后重试"
    static let BindSuccessStr = "已完成手环绑定"
    static let DataSyncing = "数据同步中"
    static let SyncDone = "数据同步完成"
    static let BraceletBattery = "手环电量"
    static let UnbindAffectNotice = "解绑后，手环将无法上传数据！"
    static let Unbinding = "解绑中~"
    
    /* alert*/
    static let ThinkLater = "再考虑下"
    static let ReChoose = "重新选择"
    static let SureWithNoDoubt = "确认无误"
    static let PleaseConfirmToWrong = "请仔细确认信息防止购卡错误！"
    
    
    static let OKCoursesOver = "——好啦，就这么多课——"
    static let OKCardsOver = "——好啦，就这么多卡——"
    static let OKFuctionsOver = "——好啦，就这么多功能——"
    
    static let GymPhoneNumber = "健身房电话"
    static let CommaPhoneNumber = "Comma健身客服"
    static let ContactNumber = "联系电话"
    static let NoNetwork = "无网络"
    
    static let Search = "搜索"
    static let CitySearchPlaceholder = "输入城市名称或拼音查询"
    static let LocCity = "定位城市"
    static let OpenCityDesc = "已开业城市"
    static let ReLocate = "重新定位"
    static let NoResult = "未搜索到结果"
    static let NotHave = "暂无"
    static let SwitchNow = "立即切换"
    static let WaitASecond = "再等一等"
    static let PleaseChooseGym = "请选择您需要的场馆进行购买操作"
    static let CurrentDefaultGym = "当前默认场馆为："
    static let PleaseWaitUntilInCityList = "该城市未开通场馆，敬请期待"
    static let YouCantBuy = "您购卡健身房与当前健身房不同\n不能进行购卡/续卡/升级卡操作"
    static let CityWideGym = "同城场馆"
    static let KingKnows = "朕知道了"
    static let FailedLocatedAndPleaseChooseGym = "定位失败，当前处于系统推荐场馆\n请手动切换场馆"
    static let CityNotInListLocatedAndPleaseChooseGym = "定位城市尚未开通场馆\n当前处于系统推荐场馆\n请手动切换场馆"
    static let Version = "版本"
    static let Wx = "微信"
    static let CooperationPhone = "商务合作电话"
    
    static let ErrorPhone = "错误的电话号码"
    
    static let CanModifyGender = "*性别仅可以修改一次，请慎重修改"
    static let CanModifyBirthday = "*出生日期仅可以修改一次，请慎重修改"
    static let CanModifyGenderAndBirthday = "*生日、性别仅可以修改一次，请慎重修改"
    
    // new user intros
    
    static let GenderIntro = "性别很重要，数据错不了"
    static let NameIntro = "默认昵称岂能符合您的气质？"
    static let AvatarIntro = "默认头像岂能表现您的颜值？"
    static let Avatar = "头像"
    static let CannotModifyAnyMore = "您的修改次数已用完\n如有疑问请联系客服"
    
    static let SwitchCity = "切换城市"
    static let HasNoCourseNow = "暂时没有课程"
    
    
    static let UserAbnormalStateDesc = "用户状态异常，如果重新登录无法解决，请联系" + AppName
    static let LoginStateOverdueDesc = "登录状态已过期，请重新登录"
    static let SureOrder = "确认订单"
    static let ClassUnit = "次课"
    static let OnceBuy = "为保证上课质量，单次最多能购买"
    static let LeastBuy = "为保证上课质量，最少购买"
    static let NutritionMealCouponDesc = "营养餐专用，无门槛使用"
    static let PrivateClassCouponDesc = "私教课专用，无门槛使用"
    static let MemberCardCouponDesc = "购卡专用，无门槛使用"
    static let GroupClassCouponDesc = "团体课专用，无门槛使用"
    static let Gym = "健身房"
    static let CardType = "卡种"
    static let Money = "金额"
    static let UnknowGym = "未知场馆"
    static let UnknowCardType = "未知卡种"
    static let TrainData = "训练数据"
    static let TrainTimes = "训练次数"
    static let TodayTrainDuration = "今日训练时间"
    static let TotalTrainDuration = "总共训练时间"
    static let CopyCode = "复制邀请码至剪贴板"
    static let YourInviteCode = "你的邀请码"
    static let InputInviteCode = "填写邀请码"
    static let LookAll = "查看全部"
    static let UsableGym = "使用场馆"
    static let UseRequirement = "使用须知"
    static let CouponUnkonwn = "当前版本App无法识别此券"
    static let Used = "已使用"
    static let Expired = "已过期"
    static let Usable = "可使用"
    static let Inconformity = "当前版本应用不适用"
    static let CouponDetailTitle = "优惠券详情"
    static let CouponGlobalUse = "适用于全国"
    
    
    static let NicknameRule = "昵称长度不得超过15个字符\n不可包含特殊字符和空格"
    
    static let WaterCharge = "水费充值"
    static let LeftTime = "剩余时间"
    static let SeletctRechargeTimeLength = "选择充值时长"
    
    static let PresentedShower  = "赠送洗澡时间"
    static let ShowerCardLimit = "若在会员卡有效期内未使用完，系统将会清空处理"
    static let LikingFitDeclare = "*LikingFit声明：禁止任何形式超过1年的会员卡\n造成任何损失和品牌无关"
    static let ReadMemberProtocolFirst = "请先阅读并同意《用户购卡协议》"
    static let ReadTrainerProtocolFirst = "请先阅读并同意《平台私教协议》"
    static let ReadTeamCourseProtocolFirst = "请先阅读并同意《平台团操课协议》"
     static let ReadlitteCourseProtocolFirst = "请先阅读并同意《购买协议》"
    static let WaterRechargeNotiDesc = "水费一经购买，不予退款，会员卡过期则水费自动失效；若有疑问，请联系健身房处理"
    
    static let LimitedTimeCard = "错峰卡"
    static let AllTimeCard = "全通卡"
    static let WaterPrice = "水费"
    static let OrderInfo = "订单详情"
    static let OfflinePay = "线下支付"
    static let LastTime = "剩余时间"
    
    static let Week = "周"
    static let Mon = "一"
    static let Tue = "二"
    static let Wed = "三"
    static let Thu = "四"
    static let Fri = "五"
    static let Sat = "六"
    static let Wee = "日"
    
    static let Jan = "一月"
    static let Feb = "二月"
    static let Mar = "三月"
    static let Apr = "四月"
    static let May = "五月"
    static let Jun = "六月"
    static let Jul = "七月"
    static let Aug = "八月"
    static let Sep = "九月"
    static let Oct = "十月"
    static let Nov = "十一月"
    static let Dec = "十二月"
    
    static let nicknameIuputLimitNotice = "昵称不可包含特殊字符和空格"
    
    // Maps
    static let AppleMap = "苹果地图"
    static let GaodeMap = "高德地图"
    static let BaiduMap = "百度地图"
    static let TencentMap = "腾讯地图"
    static let UnknownMap = "未知地图"
    
    
    static let TimeFrame = "时段"
    static let MapNavigation = "地图导航"
    static let GiftShowerTime = "赠送洗澡时间"
    static let SureBuyCard = "确认购买"
    
    static let MyCourses = "我的课程"
    static let MyOrders = "我的订单"
    static let RunOut = "到期"
    static let Complaint = "投诉"
    
    
    static let AllSportsData = "总运动"
    static let Treadmills = "跑步机"
    static let OpenedSS = "成功开启"
    
    static let OpenedSSSucceed = "成功开启SmartSpot"
    static let StartTrain = "即刻开始力量自由训练"
    static let ThxForStay = "感谢你们的陪伴"
    
    static let SportDuration = "运动时间"
    static let RestDuration = "休息时间"
    static let GroupNumber = "连续次数"
    static let Group = "组"
    static let End = "结束"
    
    static let VideoContinue = "继续播放"
    static let VideoNoWifiNotice = "当前处理非WIFI情况，是否继续播放？"
    static let NoTrainRecord = "无运动记录"
    static let Kms = "公里"
    static let Joint = "节"
    static let RunStep = "跑步"
    static let PowerTraining = "力量训练"
    static let Minutes = "分钟"
    static let ExerciseDuration = "总运动时间"
    static let KeepSportDays = "坚持运动天数"
    static let BurnCal = "燃烧卡路里"
    static let DoneSportTimes = "完成运动次数"
    static let ThousandCal = "千卡"
    static let JoinedItem = "参与的运动项目"
    static let CurrentMonth = "本月"
    static let CurrentWeek = "本周"
    static let CurrentDay = "本日"
    
    static let ClearSuccess = "清除成功"
    static let ClearFailDesc = "清除失败，请稍后重试"
    static let ClearCacheNotice = "确定要清除所有缓存数据吗？"
    static let ComputingDesc = "正在计算..."
    static let SportShareSlogan = "24小时智能健身房，随时享受FIT时刻"
    static let AllExcise = "总共运动"
    static let KeepExcise = "坚持运动"
    static let AllBurn = "累计燃烧"
    static let AchievementHouse = "成就馆"
    static let Follower = "粉丝"
    static let Following = "关注"
    
    static let Follow = "关注"
    static let Followed = "已关注"
    static let Fans = "粉丝"
    static let WinDesc = "无敌是多么寂寞！"
    static let DrawDesc = "旗鼓相当的对手"
    static let AchievementCenter = "成就馆"
    
    static let GetAchievementr = "已获得的成就"
    static let GetingAchievement = "即将获得的成就"
    static let NotGetAchievement = "未获得的成就"
    static let AchievementOpen = "展开"
    static let AchievementClose = "收起"
    static let NoTrainingDesc = "累计数据方可对战！"
    
    static let AchievementCondition = "成就条件"
    static let AchievementProgress = "成就进度"
    static let AchievementPeopleCount = "获得人数"
    static let CongratsFor = "恭喜您获得"
    static let Meet = "相遇"
    static let FollowEachOther = "互相关注"
    static let NoFansNow = "暂时没有粉丝"
    static let NoFollowerNow = "暂时没有关注"
    static let ActiveIn = "活跃在"
    static let YourDataInLikingfit = "您在CommaUser健身测试记录"
    static let ScoreHistory = "体测评分历史"
    static let NotAvailableBeforeDec2017 = "2017年12月22日以前的数据无法查看哦~"
    static let Has = "有"
    static let RunnerTogether = "一起奔跑的小伙伴"
    static let NoAchievementNow = "暂时没有成就"
    static let RunDistance = "跑步距离"
    static let RunTimeLength = "跑步时间"
    static let RunSpeed = "跑步速度"
    static let AccumulativeRunData = "在CommaUser健身累计跑步数据"
    static let ShareBodyTestData = "在CommaUser健身测试分数"
    static let CancelFollowNotice = "确定要取消关注"
    static let OpenBluetoothNotice = "打开蓝牙来允许\"\(AppName)\"连接到配件"
    
    static let NotUpdateNow = "暂不升级"
    static let UpdateNow = "立即升级"
    static let UpdateToLook = "最新CommaUser健身客户端才可以查看哦~"
    
    static let CopyrightStatement = "上海真快信息技术有限公司 版权所有"
    
    // MARK: - v 1.7.0
    static let AppointmentBox = "预约柜子"
    static let Appointing = "预约中"
    static let Using = "使用中"
    static let Appoint = "预约"
    static let OfflineUse = "线下使用"
    static let UseRecord = "使用记录"
    static let HasDone = "已完成"
    static let SureCancelOrder = "您确定取消预约吗？每天取消或逾期超过三次将无法继续预约操作！"
    static let CancelSuccess = "取消成功"
    static let AlreadyOrder = "您已预约"
    static let AlreadyUsing = "您正在使用"
    static let OrderBox = "预约柜子"
    static let BoxUseRequirement0 = "每个用户同一时间段仅可以预约或使用一台柜子；"
    static let BoxUseRequirement1 = "预约功能支持预约当前时间后15分钟的柜子；"
    static let AppointCountDown = "预约倒计时"
    static let MyTraining = "我的训练"
    static let MyCenter = "会员中心"
    static let Trainer = "私教"
    static let UploadAvatar = "上传头像"
    static let PhoneNumber = "手机号"
    static let Captcha = "验证码"
    static let countDownSuffix = "后重新发送"
    static let AnnouncementMessage = "公告消息"
    static let AnnouncementInfo = "公告详情"
    static let BraceletSearceFailNotice = "手环连接失败，请确认蓝牙是否开启"
    static let BraceletSearchOnging = "手环搜索中..."
    static let Connect = "连接"
    static let HasSearchDevice = "搜索到设备"
    static let BindSuccess = "绑定成功！"
    static let LeftElectricity = "剩余电量"
    static let MyOrder = "我的订单"
    static let SureBooking = "确认预约"
    static let NoOrder = "暂无订单"
    static let SelfHelp = "自助"
    static let BindNow = "立即绑定"
    static let DelayDecide = "以后再说"
    static let ReSearch = "重新搜索"
    static let NoHistoryData = "没有历史数据"
    static let AllRights = "© 2018 zhenkuai. All Rights Reserved"
    static let ChooseGymFirst = "请先选择场馆"
    static let BuyCardProtocol = "《用户购卡协议》"
    static let Sky = "天"
    static let OnlyMemberCanBooking = "只有会员才可以约课喔"
    static let BuyBracelet = "购买手环"
    static let VisitorOpenDoor = "访客开门"
    
    
}
